### PR TITLE
big bubatz 👍

### PR DESCRIPTION
**Pull request by Traction6131**
haha I totally didnt do that with gibubs web ui

### CODE REVIEW

**Comment by Traction6131** [comment]
I like rabbib and flof birb 😄

**Comment by sys-256** [comment]
sir you bozo you forgor to add the form class

**Comment by sys-256** [comment]
also plz use the form-input class instead of form (to avoid confusion with the form tag)

**Comment by Traction6131** [comment]
elo

**Comment by Traction6131** [comment]
> also plz use the form-input class instead of form

why

**Comment by sys-256** [comment]
check edit :relieved:

**Pull request closed without merging**
